### ISSUE TITLE
Who questions 

### ISSUE THREAD

**Issue by MSherif** [dbpedia/chatbot#9] opened 2017-08-01 10:43 UTC
Who questions should always return an entity of type person or nothing.
For example when trying "Who is el sisi?" the system returns an airline company.

Also, trying "Who is El-Sisi?" returns the write entity, which indicate the need of applying some string similarities for labels.

**Comment by RicardoUsbeck** [comment] 2017-08-02 06:55
The problem is within the QA engine we currently, i.e. wdaqua. Maybe @D063520 knows more.

**Comment by D063520** [comment] 2017-08-02 08:31
Mhmm, can you say me what API you are using. Because when I try on DBpedia the same question I get the right answer: 

https://wdaqua-frontend.univ-st-etienne.fr/question?query=Who%20is%20El-Sisi?&lang=en&kb=dbpedia

https://wdaqua-frontend.univ-st-etienne.fr/question?query=Who%20is%20el%20sisi?&lang=en&kb=dbpedia

In wikidata this is not the case, I'm trying to teach him what to do ; )

Salut
Dennis

**Comment by D063520** [comment] 2017-08-02 12:25
ok, should work also over wikidata now:

https://wdaqua-frontend.univ-st-etienne.fr/question?query=Who%20is%20Trump?%20&lang=en&kb=wikidata

Salut Dennis

**Comment by RicardoUsbeck** [comment] 2017-09-13 19:16
@ram-g-athreya is that resolved?

**Comment by ram-g-athreya** [comment] 2017-09-14 02:48
I think this is resolved now. I will close it for now.

**Closed as completed by ram-g-athreya** 2017-09-14 02:48 UTC
Labels: bug
